version: '2'
services:
  roscore_node:
    image: "robotcore"
    container_name: roscore_node
    environment:
      - "ROS_IP=192.168.3.118"
    network_mode: "host"
    environment:
      - "HOST_OS=linux"
      - "Robotmaster_Service_Port=8000"

  robotmaster_node:
    image: "robotmaster"
    container_name: robotmaster_node
    network_mode: "host"
    environment:
      - "HOST_OS=linux"
      - "Robotmaster_Service_Port=8000"
      - "ROS_IP=192.168.3.118"
      - "ROS_MASTER_URI=http://192.168.3.118:11311"
      - "TURTLEBOT3_MODEL=waffle_pi"
    volumes:
      - /home/sw/projects/rosbot:/root/projects
    ports:
      - "8000:8000"

