version: '2'
services:
  roscore_node:
    image: "robotcore"
    container_name: roscore_node
    environment:
      - "ROS_IP=192.168.27.1"
    network_mode: "host"
    environment:
      - "HOST_OS=linux"

  robotmaster_node:
    image: "robotmaster"
    container_name: robotmaster_node
    network_mode: "host"
    environment:
      - "HOST_OS=linux"
      - "ROS_IP=192.168.27.1"
      - "ROS_MASTER_URI=http://192.168.27.1:11311"
      - "TURTLEBOT3_MODEL=waffle_pi"
    volumes:
      - /home/sw/projects/rosbot:/root/projects
    ports:
      - "8100:8100"

