version: '2'
services:
  robotmaster_node:
    image: "robotcore"
    container_name: robotcore_node
    environment:
      - "ROS_IP=192.168.27.1"
    network_mode: "host"
    environment:
      - "HOST_OS=linux"
